### ISSUE TITLE
Rename tab heading from "AdEx dApp" to "AdEx Platform" 

### ISSUE THREAD

**Issue by Dylanoshi** [AdExNetwork/adex-dapp#67] opened 2019-05-07 02:27 UTC
in concert with our repositioning to a 'platform'

**Comment by IvoPaunov** [comment] 2019-05-07 10:35
Duplicate of #51

**Comment by IvoPaunov** [comment] 2019-05-07 10:36
[Done](https://github.com/AdExNetwork/adex-dapp/commit/c8c0e42ba8b61e398055113559c8006c05a8dd32)

**Closed by IvoPaunov** 2019-05-07 10:36 UTC
